name: Build Base
on: workflow_dispatch
env:
  DOCKER_REPO: etcdnecx

jobs:
  build-arm64:
    name: Build ARM64
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v5.2.0
          platforms: arm64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          TAG=base-ovs-arm make  base-ovs-arm64
          TAG=base-ovs-arm make  base-tar-ovs-arm64
          
      - name: Upload image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-ovs-arm64
          path: image-ovs-arm64.tar
  push:
    needs:
      - build-arm64
    name: push
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3 
        
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: image-ovs-arm64

      - name: Load Image
        run: |
          docker load --input image-ovs-arm64.tar

      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
          TAG: ${{ github.ref_name }}
        run: |
          TAG=$(echo ${TAG} | sed 's/ecx-//g')
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker tag kube-ovn/kube-ovn:base-ovs-arm-arm64  $DOCKER_REPO/kube-ovn:base-ovs-arm
          docker push $DOCKER_REPO/kube-ovn:base-arm-ovs
