name: Push Multi Arch Image
on:
  workflow_run:
    workflows: ["Build arm64 Image", "Build x86 Image"]
    branches:
      - ecx-*
    types:
      - completed

jobs:
  build:
    name: Push multi arch images
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Login to DEV Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DEV_REGISTRY }}
          username: ${{ secrets.DEV_HARBOR_USERNAME }}
          password: ${{ secrets.DEV_HARBOR_TOKEN }}

      - name: Login to TAG Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.PRO_REGISTRY }}
          username: ${{ secrets.PRO_HARBOR_USERNAME }}
          password: ${{ secrets.PRO_HARBOR_TOKEN }}

      - name: Push
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          TAG: ${{ github.ref_name }}
          REF: ${{ github.ref }}
          DEV_REGISTRY: ${{ vars.DEV_REGISTRY }}
          TAG_REGISTRY: ${{ vars.PRO_REGISTRY }}
        run: |
          TAG=$(echo ${TAG} | sed 's/ecx-//g')

          docker pull $DEV_REGISTRY/kube-ovn:$TAG-x86
          docker pull $DEV_REGISTRY/kube-ovn:$TAG-arm
          docker manifest create $DEV_REGISTRY/kube-ovn:$TAG $DEV_REGISTRY/kube-ovn:$TAG-x86 $DEV_REGISTRY/kube-ovn:$TAG-arm
          docker manifest push $DEV_REGISTRY/kube-ovn:$TAG
